DB側での制約をモデルにも反映
elca-hub/time_schedule pull request #5
Opened 2023-05-09 07:18 UTC by elca-hub

# DB側での制約をモデルにも反映

## Added
- User、Taskモデルに、DB側で記述していた制約と同じ制約を追加

## issue

close #2

2023-05-09 07:50 UTC, waruru commented on app/models/user.rb
>  end
ファイルの行末は改行入れておくといいです。
改行がないとこのようなマークが出ます

2023-05-09 08:28 UTC, waruru commented on app/models/user.rb
> +    validates :name, length: {minimum:1, maximum:100}, uniqueness: true
コメントミス🙏
minimumを消した方がいい

2023-05-09 09:53 UTC, elca-hub commented on app/models/user.rb
> +    validates :name, length: {minimum:1, maximum:100}, uniqueness: true
了解です！

2023-05-09 14:22 UTC, waruru commented on app/models/task.rb
> +    validates :content, uniqueness: true, presence: true
ここに関してユニーク制約をつけて大丈夫かな？

2023-05-09 15:44 UTC, elca-hub commented on app/models/task.rb
> +    validates :content, uniqueness: true, presence: true
普通にダメでした....

2023-05-12 00:16 UTC, waruru requested changes
確認遅くなってごめん🙏
変更は大丈夫だったので、コンフリクト修正ができればOKです！

2023-05-12 00:22 UTC, elca-hub reviewed
提案された箇所を修正

2023-05-12 00:24 UTC, waruru approved these changes
LGTM
![LGTM](https://image.lgtmoon.dev/208266)

2023-05-12 00:25 UTC, merged